// Code generated by hertz generator.

package main

import (
	handler "cex-hertz/biz/handler"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)
	r.POST("/api/order", handler.SubmitOrder)

	// your code ...
	// WebSocket 路由已独立服务，无需在此注册 /ws
}
