// Code generated by hertz generator.

package main

import (
	handler "cex-hertz/biz/handler"
	"cex-hertz/middleware"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	orderGroup := r.Group("/api")
	orderGroup.Use(middleware.DistributedRouteMiddleware())
	orderGroup.POST("/order", handler.SubmitOrder)
}
